### ISSUE TITLE
External secrets for cloudflare-tunnel-remote

### ISSUE THREAD

**Issue by mergwyn** [cloudflare/helm-charts#48] opened 2023-08-14 13:15 UTC
It does not seem to possible to create the tunnel_token as a secret separate from the values.yaml file as #38 has implemented for the Cloudflare-tunnel chart so that it can be stored securely (eg in GitHub)

**Comment by uhthomas** [comment] 2023-08-15 11:36
Duplicate of #36

**Closed** 2023-08-15 11:39 UTC
